esphome:
  name: "carrier-42aaf"
  includes: 
    - carrier.h
  libraries:
    - IRremoteESP8266@2.8.6
    - EEPROM

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret api_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "YOUR-OWN-SSID"
    password: "YOUR-OWN-PASSWORD"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "AC WiFi Strength"
    update_interval: 60s
  - platform: uptime
    name:  "AC Uptime"

binary_sensor:
  - platform: status
    name: "AC Connectivity"

climate:
  - platform: custom
    lambda: |-
      auto my_ac = new CarrierAC(id(light_switch));
      App.register_component(my_ac);
      return {my_ac};
    climates:
      - name: "AC"
        id: my_ac

switch:
  - platform: restart
    name: "AC Reboot Switch"
  - platform: custom
    lambda: |-
      auto light_sw = new CarrierACLightSwitch();
      App.register_component(light_sw);
      return {light_sw};
    switches:
      name: "AC Light"
      id: light_switch
